# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 16.0
org_name: Akretion
org_slug: akretion
rebel_module_groups: []
repo_description: Odoo module to export journal entries to another accounting software
repo_name: Account Move Export
repo_slug: 'https://github.com/akretion/account-move-export '
repo_website: 'https://github.com/akretion/account-move-export '
use_pyproject_toml: false
use_ruff: true

